edit_uri: edit/main/docs
extra_css:
- stylesheets/custom.css
extra_javascript:
- javascripts/custom.js
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
nav:
- Git:
  - Git 01: git/git_01.md
- Java:
  - Java-01: java/java-01.md
  - Java-02: java/java-02.md
repo_name: GitHub
repo_url: https://github.com/carami/likelion-backend-guide
site_description: Markdown 기반의 깔끔한 강의 웹페이지
site_name: 멋쟁이 사자처럼 백엔드 부트캠프
theme:
  logo: likelion_kor_logo_renew.svg
  name: material
