theme:
  logo: images/likelion_kor_logo_renew.svg
  name: material
edit_uri: edit/main/docs
extra_css:
- stylesheets/custom.css
extra_javascript:
- javascripts/custom.js
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
nav:
- 홈: index.md
- 교안:
  - Git:
    - Git 01: git/git_01.md
  - Java:
    - Java-01 준비: java/java-01_준비.md
    - Java-02 소개: java/java-02_소개.md
- 체크리스트:
  - checklist/week01.md
  - checklist/week02.md
- FAQ: faq.md
repo_name: GitHub
repo_url: https://github.com/carami/likelion-backend-guide
site_description: Markdown 기반의 깔끔한 강의 웹페이지
site_name: 백엔드 부트캠프
