name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Setup Git Identity
        run: |
          git config --global user.email "carami@nate.com"
          git config --global user.name "carami"

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
